### ISSUE TITLE
Fatal Error - Failed to execute script BGS Companion

### ISSUE THREAD

**Issue by cyberbofh** [breca/elite_bgs_companion#32]
When trying to run the BGS Companion app, I get the following error:

**Fatal Error - Failed to execute script BGS Companion**

companion.log only shows this:

`2019-05-03 18:49:31,227 - root - INFO - Started.`
`2019-05-03 18:51:07,773 - root - INFO - Started.`
`2019-05-03 18:58:11,079 - root - INFO - Started.`
`2019-05-03 19:02:46,753 - root - INFO - Started.`
`2019-05-03 19:03:10,516 - root - INFO - Started.`
`2019-05-03 19:03:10,610 - PIL.PngImagePlugin - DEBUG - STREAM b'IHDR' 16 13`
`2019-05-03 19:03:10,611 - PIL.PngImagePlugin - DEBUG - STREAM b'sRGB' 41 1`
`2019-05-03 19:03:10,611 - PIL.PngImagePlugin - DEBUG - STREAM b'gAMA' 54 4`
`2019-05-03 19:03:10,611 - PIL.PngImagePlugin - DEBUG - STREAM b'pHYs' 70 9`
`2019-05-03 19:03:10,611 - PIL.PngImagePlugin - DEBUG - STREAM b'IDAT' 91 6267`

I did change the loglevel in **settings.ini** to debug, hoping it would give some useful info

I downloaded the app again, unzipped it over the "old" one and tried again, but getting the same error.
Last time it worked: 2019-05-03

Please advise

**Comment by breca** [comment]
I'm actually pretty amazed that someone is still using this let alone that it's working. I don't really play Elite anymore and haven't looked at this for a long time.

Only advice I could give is to see if you can replicate the issue with a fresh install of the companion - delete the old directory entirely and start with a fresh copy.

Good luck!

**Comment by cyberbofh** [comment]
<<insert head banging against wall>>

Ok, like I said before, I did use a new install, but.. unpacked the zip in the old folder
Now I have deleted the folder first and then unpacked and started the app, it works OK


About the game:

- there is still lots of grinding
- there are still lots of (stupid) unneeded bugs thanks to lack of proper testing and quality control

but..

- there are still lots of beautiful things to discover
- it's still fun to wing up together and have some fun

and your tool is a nice one to keep track on things :)
Maybe you should give the game a try again? Feel free to wing up with me in the cold dark space of Elite ;)



Status: Problem solved by a fresh install, you can close it

**Comment by breca** [comment]
I'm glad you're still getting some use out of it, I'm sure I'll come back and see how the game is going at some point.
Appreciate the update!
